name: validate student sites
on: pull_request
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check folders and files
        run: |
          set -e
          shopt -s nullglob
          for d in public/sites/*/; do
            name=$(basename "$d")
            [[ "$name" =~ ^[a-z0-9-]+$ ]] || { echo "❌ nombre inválido: $name"; exit 1; }
            test -f "$d/index.html" || { echo "❌ falta index.html en $d"; exit 1; }
          done
          echo "✅ OK"
