apiVersion: v1
kind: Service
metadata:
  name: {{ include "saas-api.fullname" . }}
  labels:
    {{- include "saas-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3333
      protocol: TCP
      name: http
  selector:
    app: {{ include "saas-api.name" . }}
