global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:9464']
  - job_name: web
    metrics_path: /metrics
    static_configs:
      - targets: ['web:9464']
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgres
