apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saas-web.fullname" . }}
  labels:
    {{- include "saas-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "saas-web.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "saas-web.name" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
