apiVersion: v1
kind: Service
metadata:
  name: {{ include "saas-web.fullname" . }}
  labels:
    {{- include "saas-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "saas-web.name" . }}
