apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: saas-web-sec-headers
  namespace: saas
spec:
  headers:
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    contentTypeNosniff: true
    browserXssFilter: true
    contentSecurityPolicy: "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.example.com https://app.posthog.com"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: saas-api-sec-headers
  namespace: saas
spec:
  headers:
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    contentTypeNosniff: true
    browserXssFilter: true
    contentSecurityPolicy: "default-src 'none'; frame-ancestors 'none'; connect-src 'self';"
