remote_theme: just-the-docs/just-the-docs
plugins: [jekyll-remote-theme]

title: DevSyllabus — Entry Level
description: Curso con videos, quizzes y labs
logo: /assets/logo.svg
color_scheme: light

nav_external_links:
  - title: Mi primera web (HTML)
    url: /public/
  - title: Módulo 01
    url: /modulos/01-html-basico.html
  - title: Roadmap
    url: /modulos/00-scratch.html
  - title: Full Stack
    url: /fullstack/00-onboarding.html
