apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/saas-devops-first.git
    targetRevision: main
    path: infra/helm/api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: saas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: saas-api
      namespace: saas
