image:
  repository: ghcr.io/your-org/saas/web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - app.example.com
      secretName: web-tls

env:
  NEXT_PUBLIC_APP_URL: https://app.example.com
  NODE_ENV: production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
